version: '3.9'

services:
  server:
    image: jagdeepminhas/backend-app
    ports: 
      - "8080:8080"
  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
  frontend:
    image: jagdeepminhas/frontend-app 
    ports:
      - "3000:3000" 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8081 
