version: '3.9'

services:
  server:
    build: ./Backend  # Assuming your backend Dockerfile is in the 'backend' directory
    ports: 
      - "8081:8080"
  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
  frontend:
    build: ./Frontend  # Assuming your frontend Dockerfile is in the 'frontend' directory
    ports:
      - "3000:3000"  # Map the port your frontend serves on to the same port on the host
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8081  # Environment variable for the backend URL, adjust as needed
